platform :ios, '10.3'

target 'CRMobileChallenge' do
  use_frameworks!
  
  pod 'SwiftMessages'
  
  target 'CRMobileChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Domain' do
  use_frameworks!
  
  target 'DomainTests' do
    inherit! :search_paths
  end

end

target 'Shared' do
  use_frameworks!

  pod 'Kingfisher'

  target 'SharedTests' do
    inherit! :search_paths
  end

end
